### ISSUE TITLE
Deploying BIGIP Next using tf with vsphere

### ISSUE THREAD

**Issue by sebbycorp** [F5Networks/terraform-provider-bigipnext#34]
Hi there,
resource "bigipnext_cm_deploy_vmware" "vmware" {
  vsphere_provider = {
    provider_name      = "vc.maniak.lab"
    content_library    = "BIG-IP-NEXT"
    cluster_name       = "MyCluster"
    datacenter_name    = "Datacenter"
    datastore_name     = "datastore1"
    resource_pool_name = "Resources"
    vm_template_name   = "BIG-IP-Next-20.2.1"
  }
  instance = {
    instance_hostname     = "f5next-001.maniak.lab"
    mgmt_address          = "172.16.10.22"
    mgmt_prefix           = 24
    mgmt_gateway          = "172.16.10.1"
    mgmt_network_name     = "VM Network"
    mgmt_user             = "admin-cm"
    mgmt_password         = "W3lcome098!"
    external_network_name = "VM Network"
    
    cpu = "2"
    memory = "8192"
  }
  ntp_servers = ["0.us.pool.ntp.org"]
  dns_servers = ["8.8.8.8"]
  timeout     = 1200
}

I am getting this error ? bigipnext_cm_deploy_vmware.vmware: Still creating... [18m0s elapsed]
╷
│ Error: Client Error
│ 
│   with bigipnext_cm_deploy_vmware.vmware,
│   on main.tf line 1, in resource "bigipnext_cm_deploy_vmware" "vmware":
│    1: resource "bigipnext_cm_deploy_vmware" "vmware" {
│ 
│ Failed to Deploy Instance, got error: DEVICE-0206: BIG-IP Next instance discovery error: FailedToStoreL3Network 

do i need to set network ?

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1666.

**Comment by RavinderReddyF5** [comment]
Hi @sebbycorp , we did not run into this issue, but on latest version of v20.3.0 we got different issue, which will be addressing through  INFRAANO-1666

**Comment by RavinderReddyF5** [comment]
Hi @sebbycorp ,
please verify issue with v1.3.0 on Central manager Orange version.
