### ISSUE TITLE
Cannot deploy Next tenant through VELOS provider

### ISSUE THREAD

**Issue by F5JC** [F5Networks/terraform-provider-bigipnext#4]
Hi there,

hen attempting to deploy Next instance through CM configured with a VELOS provider, it appears TF is actually requesting for a Rseries provider to be used.

### Terraform Version
Terraform v1.7.5
on linux_amd64

### Affected Resource(s)
bigipnext_cm_deploy_f5os

### Terraform Configuration Files
provider "bigipnext" {
  username = "admin"
  password = ">admin_pwd>"
  host     = "https://10.155.43.129"
}
resource "bigipnext_cm_deploy_f5os" "velos01" {
  f5os_provider = {
    provider_name = "gslabvelosprovider"
    provider_type = "velos"
  }
  instance = {
    instance_hostname      = "danjontfnext01"
    management_address     = "10.154.78.119"
    management_prefix      = 24
    management_gateway     = "10.154.78.254"
    management_user        = "admin-cm"
    management_password    = "test123"
    vlan_ids               = [525]
    tenant_deployment_file = "BIG-IP-Next-20.0.2-2.139.10+0.0.165.yaml"
    tenant_image_name      = "BIG-IP-Next-20.0.2-2.139.10+0.0.165"
  }
}

### Debug Output
Failed to Deploy Instance, got error: mismatched provider ID vs. type: provider id "7ffa8b89-5027-406a-a234-12725ed5877a" is a "VELOS" provider, not a RSERIES provider

### Expected Behavior
TF should be requesting CM to create instance through the VELOS provider: CM is configured with one VELOS provider only, and .tf files mentions "velos" as a "platform_type"

### Actual Behavior
With reviewing API calls & traffic, from packets, it appears:
1. TF retrieves the properties of the CM provider:
GET /api/device/v1/providers?filter=name+eq+'gslabvelosprovider'
... and get response this is VELOS - pls note the use of capital letter - provider:

HTTP/1.1 200 OK
[...]
[{"instances":[],"provider_host":"10.154.78.118:8888","provider_id":"4b58f9ae-0588-4ff7-bffe-a22173890e61","provider_name":"gslabvelosprovider","provider_type":"VELOS","provider_username":"admin","updated":"2024-03-30T15:02:13.267674Z"}]

2. Then, TF requests the Next instance to get created but it requests for a "rseries" provider:
POST /api/device/v1/instances
[...]
{"template_name":"default-standalone-rseries","parameters":{"instantiation_provider":[{"id":"4b58f9ae-0588-4ff7-bffe-a22173890e61","name":"gslabvelosprovider","type":"rseries"}] [...] <--- [!!]

### Steps to Reproduce
Simpy use .tf/declaration above + have CM configured with a VELOS provider

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1536.

**Comment by F5JC** [comment]
Hello,

I just ran a few tests with "bigipnext" provider 1.0.1.
And it seems the issue's fixed.

**Comment by pgouband** [comment]
Hi @F5JC,

Thanks, I'll close it.
